# Generated by Django 4.2.3 on 2023-07-28 00:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('سیکو', 'سیکو'), ('ارینت', 'ارینت'), ('سیتیزن', 'سیتیزن'), ('کاسیو', 'کاسیو'), ('جی شاک', 'جی شاک'), ('رولکس', 'رولکس'), ('پتک فیلیپ', 'پتک فیلیپ'), ('امگا', 'امگا'), ('تگ هویر', 'تگ هویر'), ('رومانسون', 'رومانسون'), ('فردریک کنستانت', 'فردریک کنستانت'), ('فسیل', 'فسیل'), ('کنت کول', 'کنت کول'), ('اسکادا', 'اسکادا'), ('دوفا', 'دوفا'), ('اسکاگن', 'اسکاگن'), ('بستدان', 'بستدان')], max_length=100, verbose_name='برند')),
                ('nationality', models.CharField(choices=[('CHINA', 'چین'), ('SWITZERLAND', 'سوئیس'), ('JAPAN', 'ژاپن'), ('AMERICA', 'آمریکا'), ('DENMARK', 'دانمارک'), ('ENGLAND', 'انگلیس'), ('ITALY', 'ایتالیا'), ('GERMANY', 'آلمان'), ('AUSTRIA', 'اتریش'), ('AUSTRALIA', 'استرالیا'), ('OTHER', 'دیگر')], max_length=50, verbose_name='ملیت')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برند ها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام رنگ')),
                ('value', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد رنگ')),
            ],
            options={
                'verbose_name': 'رنگ',
                'verbose_name_plural': 'رنگ ها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, max_length=250, null=True, verbose_name='مدل')),
                ('sex', models.CharField(choices=[('مردانه', 'مردانه'), ('زنانه', 'زنانه'), ('اسپرت', 'اسپرت')], max_length=50, verbose_name='جنسیت')),
                ('style', models.CharField(choices=[('نظامی', 'نظامی'), ('کژال', 'کژال'), ('مسابقه ای', 'مسابقه ای'), ('غواصی', 'غواصی'), ('جنگی', 'جنگی'), ('فشن', 'فشن'), ('لاکچری', 'لاکچری'), ('هوشمند', 'هوشمند'), ('اسپرت', 'اسپرت'), ('خلبانی', 'خلبانی'), ('رسمی', 'رسمی'), ('دیگر', 'دیگر')], max_length=100, verbose_name='استابل')),
                ('engine_type', models.CharField(choices=[('مکانیکی', 'مکانیکی'), ('اتوماتیک', 'اتوماتیک'), ('کوارتز', 'کوارتز'), ('دیگر', 'دیگر')], max_length=100, verbose_name='نوع موتور')),
                ('dial_type', models.CharField(choices=[('اسکلتون', 'اسکلتون'), ('قلب باز', 'قلب باز'), ('ساده', 'ساده')], max_length=100, verbose_name='نوع صفحه')),
                ('strap_type', models.CharField(choices=[('صدفی', 'صدفی'), ('جوبیلی', 'جوبیلی'), ('مشبک', 'مشبک'), ('ناتو', 'ناتو'), ('لاستیکی', 'لاستیکی'), ('پرلون', 'پرلون'), ('چرم کژال', 'چرم کژال'), ('مهندسی', 'مهندسی'), ('پارچه بادبانی', 'پارچه بادبانی'), ('زولو', 'زولو'), ('چرم رالی', 'چرم رالی'), ('خلبانی', 'خلبانی'), ('دیگر', 'دیگر')], max_length=100, verbose_name='نوع بند')),
                ('glass_material', models.CharField(choices=[('آکریلیک', 'آکریلیک'), ('منیرال', 'منیرال'), ('منیرال سخت', 'منیرال سخت'), ('سافایر', 'سافایر'), ('سافایر کریستال', 'سافایر کریستال'), ('کریستال یاقوت کبود', 'کریسال یاقوت کبود'), ('پی وی سی', 'پی وی سی'), ('دیگر', 'دیگر')], max_length=100, verbose_name='جنس شیشه')),
                ('strap_material', models.CharField(choices=[('چرم', 'چرم'), ('استیل', 'استیل'), ('سیلیکون', 'سیلیکون'), ('نایلون', 'نایلون'), ('پارچه', 'پارچه'), ('تیتانیوم', 'تیتانیوم'), ('سرامیک', 'سرامیک'), ('آلومینیوم', 'آلومینیوم'), ('نقره', 'نقره'), ('برنز', 'برنز'), ('کربن', 'کربن'), ('برنج', 'برنج'), ('دیگر', 'دیگر')], max_length=100, verbose_name='جنس بند')),
                ('water_resistance', models.CharField(choices=[('1ATM', '1 ATM'), ('3ATM', '3 ATM'), ('5ATM', '5 ATM'), ('10ATM', '10 ATM'), ('20ATM', '20 ATM'), ('not', 'not')], max_length=10, verbose_name='میزان مقاومت در برابر آب')),
                ('weight', models.PositiveIntegerField(default=0, verbose_name='وزن')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='قیمت')),
                ('off', models.PositiveIntegerField(default=0, verbose_name='درصد تخفیف')),
                ('new_price', models.PositiveIntegerField(verbose_name='قیمت پس از تخفیف')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='موجودی')),
                ('slug', models.SlugField(max_length=250, verbose_name='اسلاگ')),
                ('publish', django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('create', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('update', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PB', 'Published'), ('DR', 'Drafted'), ('RJ', 'Rejected')], default='DR', max_length=2, verbose_name='وضعیت')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_watched', to='product.brand', verbose_name='برند')),
                ('case_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='product.color', verbose_name='رنگ قالب')),
                ('dial_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dials', to='product.color', verbose_name='رنگ صفحه')),
                ('strap_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='straps', to='product.color', verbose_name='رنگ بند')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['-publish'],
            },
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['name'], name='product_bra_name_48e1c4_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-publish'], name='product_pro_publish_206d0e_idx'),
        ),
    ]
