# Generated by Django 4.2.3 on 2023-07-28 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='persian_name',
            field=models.CharField(default='', max_length=100, verbose_name='نام فارسی برند'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=100, verbose_name='برند'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='nationality',
            field=models.CharField(max_length=50, verbose_name='ملیت'),
        ),
    ]
