# Generated by Django 4.2.3 on 2023-07-30 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_brand_persian_name_alter_brand_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='نام و نام انوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('subject', models.CharField(max_length=250, verbose_name='موضوع')),
                ('message', models.TextField(verbose_name='پیام')),
            ],
            options={
                'verbose_name': 'تیکت',
                'verbose_name_plural': 'تیکت ها',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='dial_type',
            field=models.CharField(choices=[('اسکلتون', 'اسکلتون'), ('قلب باز', 'قلب باز'), ('مینیمال', 'مینیمال')], max_length=100, verbose_name='نوع صفحه'),
        ),
        migrations.AlterField(
            model_name='product',
            name='new_price',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت پس از تخفیف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='style',
            field=models.CharField(choices=[('نظامی', 'نظامی'), ('کلاسیک', 'کلاسیک'), ('مسابقه ای', 'مسابقه ای'), ('غواصی', 'غواصی'), ('جنگی', 'جنگی'), ('فشن', 'فشن'), ('لاکچری', 'لاکچری'), ('هوشمند', 'هوشمند'), ('اسپرت', 'اسپرت'), ('خلبانی', 'خلبانی'), ('رسمی', 'رسمی'), ('دیگر', 'دیگر')], max_length=100, verbose_name='استابل'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.PositiveIntegerField(default=0, verbose_name='وزن بر حسب گرم'),
        ),
    ]
