# Generated by Django 4.2.3 on 2023-07-31 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='seen',
            field=models.BooleanField(default=False, verbose_name='دیده شده'),
        ),
    ]
