# Generated by Django 4.2.3 on 2023-08-02 20:48

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image_file',
            field=django_resized.forms.ResizedImageField(crop=None, default='', force_format=None, keep_meta=True, quality=-1, scale=None, size=[1920, 1080], upload_to='brand_images/'),
            preserve_default=False,
        ),
    ]
